# Generated by Django 5.2.9 on 2025-12-14 13:00

import django.db.models.deletion
import django.utils.timezone
import myblog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="名称",
                    ),
                ),
                ("color", models.CharField(max_length=32, verbose_name="颜色")),
                (
                    "item_count_cache",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="关联数量"
                    ),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
            },
        ),
        migrations.CreateModel(
            name="StoragePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_object_storage",
                    models.BooleanField(default=False, verbose_name="启用对象存储上传"),
                ),
                (
                    "cdn_domain",
                    models.URLField(
                        blank=True, default="", verbose_name="CDN 域名/直链前缀"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "存储偏好",
                "verbose_name_plural": "存储偏好",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="名称",
                    ),
                ),
                ("color", models.CharField(max_length=32, verbose_name="颜色")),
                (
                    "item_count_cache",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="关联数量"
                    ),
                ),
            ],
            options={
                "verbose_name": "文章标签",
                "verbose_name_plural": "文章标签",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "Userid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "该用户名已被使用。"},
                        help_text="必填。150个字符或更少。只能包含字母、数字和 @/./+/-/_ 字符。",
                        max_length=150,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="个性签名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.CreateModel(
            name="Blogpost",
            fields=[
                (
                    "Blog_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="文章ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="标题"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("Vissible", models.BooleanField(default=True, verbose_name="公开性")),
                ("Content", models.TextField(blank=True, verbose_name="文章内容")),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=myblog.models.cover_upload_to,
                        verbose_name="封面图",
                    ),
                ),
                (
                    "cover_object_url",
                    models.URLField(
                        blank=True, default="", max_length=1024, verbose_name="封面直链"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="是否置顶"),
                ),
                (
                    "Blog_status",
                    models.IntegerField(
                        choices=[(0, "草稿"), (1, "已发布"), (2, "已删除")],
                        db_index=True,
                        default=0,
                        verbose_name="文章状态",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogposts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="myblog.classification",
                        verbose_name="文章分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="myblog.tag",
                        verbose_name="文章标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "Comment_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="评论ID"
                    ),
                ),
                (
                    "Comment_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="评论时间"
                    ),
                ),
                (
                    "Comment_content",
                    models.TextField(blank=True, verbose_name="评论内容"),
                ),
                (
                    "Comment_status",
                    models.IntegerField(
                        choices=[(0, "草稿"), (1, "已发布"), (2, "已删除")],
                        default=0,
                        verbose_name="评论状态",
                    ),
                ),
                (
                    "Comment_banned",
                    models.BooleanField(default=False, verbose_name="是否封禁"),
                ),
                (
                    "Comment_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="myblog.blogpost",
                        verbose_name="评论文章",
                    ),
                ),
                (
                    "Comment_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="myblog.comment",
                        verbose_name="上级评论",
                    ),
                ),
                (
                    "Comment_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["-Comment_time"],
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=myblog.models.post_image_upload_to,
                        verbose_name="图片",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "object_storage_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="对象存储直链",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="myblog.blogpost",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章图片",
                "verbose_name_plural": "文章图片",
            },
        ),
    ]
